const ReasonCodes = Object.freeze({
  MRZ_CHECKSUM_FAILED: 'MRZ_CHECKSUM_FAILED',
  DOB_UNPARSEABLE: 'DOB_UNPARSEABLE',
  DUPLICATE_PASSPORT: 'DUPLICATE_PASSPORT',
  GEMINI_TIMEOUT: 'GEMINI_TIMEOUT',
  GEMINI_DISABLED: 'GEMINI_DISABLED',
  GEMINI_BAD_RESPONSE: 'GEMINI_BAD_RESPONSE',
  GEMINI_AUTH_FAILED: 'GEMINI_AUTH_FAILED',
  GEMINI_TRANSIENT: 'GEMINI_TRANSIENT',
  REQUIRED_FIELD_MISSING: 'REQUIRED_FIELD_MISSING',
  IPC_INVALID_ARGS: 'IPC_INVALID_ARGS',
  IMPORT_NO_PASSPORT: 'IMPORT_NO_PASSPORT',
  IMPORT_DOB_UNPARSEABLE: 'IMPORT_DOB_UNPARSEABLE',
  IMPORT_JSON_BAD_ELEMENT: 'IMPORT_JSON_BAD_ELEMENT',
  IMPORT_PDF_NO_TABLE: 'IMPORT_PDF_NO_TABLE',
  IMPORT_FORMAT_UNSUPPORTED: 'IMPORT_FORMAT_UNSUPPORTED',
  IMPORT_FILE_UNREADABLE: 'IMPORT_FILE_UNREADABLE'
});

module.exports = { ReasonCodes };
